language: swift
osx_image: xcode11
script: 
  - xcodebuild -sdk iphonesimulator -project ./AttributedTextSample.xcodeproj -scheme AttributedTextSample -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.0' test
after_success:
  - bash <(curl -s https://codecov.io/bash)
